In [31]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json
import pandas as pd
import os 
from time import time
from time import sleep

In [32]:
def api_runner():

    global df
    url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
    parameters = {
    'start':'1',
    'limit':'15',
    'convert':'USD'
    }
    headers = {
    'Accepts': 'application/json',
    'X-CMC_PRO_API_KEY': '43db1252-631f-4d19-b123-219504e18519',
    }

    session = Session()
    session.headers.update(headers)

    try:
        response = session.get(url, params=parameters)
        data = json.loads(response.text)
        #print(data)
    except (ConnectionError, Timeout, TooManyRedirects) as e:
        print(e)

    df = pd.json_normalize(data['data'])
    df['timestamp'] = pd.to_datetime('now')
    #df = df.append(df2)
    df
    if not os.path.isfile(r'/Users/apple/Desktop/Python Projects/API.csv'):
        df.to_csv(r'/Users/apple/Desktop/Python Projects/API.csv', header = 'column_names')
    else:
         df.to_csv(r'/Users/apple/Desktop/Python Projects/API.csv', mode = 'a', header = False)

In [33]:

for i in range(12):
    api_runner()
    print('API runner completed successfully.')
    sleep(5) #sleep for 1 minute
exit()

/var/folders/s3/xb408jb53h775z4pp_qsd23w0000gn/T/ipykernel_41162/3905299087.py:26: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df['timestamp'] = pd.to_datetime('now')

API runner completed successfully.

/var/folders/s3/xb408jb53h775z4pp_qsd23w0000gn/T/ipykernel_41162/3905299087.py:26: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df['timestamp'] = pd.to_datetime('now')

API runner completed successfully.

/var/folders/s3/xb408jb53h775z4pp_qsd23w0000gn/T/ipykernel_41162/3905299087.py:26: FutureWarning: The parsing of 'now' in pd.to_datetime without `utc=True` is deprecated. In a future version, this will match Timestamp('now') and Timestamp.now()
  df['timestamp'] = pd.to_datetime('now')

API runner completed successfully.

KeyboardInterrupt:

In [35]:
df_file = pd.read_csv("/Users/apple/Desktop/Python Projects/API.csv")

In [29]:
pd.set_option('display.float_format', lambda x: '%.2f' %x)

In [36]:
df_file

,Unnamed: 0,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,...,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address,timestamp
0,0,1,Bitcoin,BTC,bitcoin,9863,2013-04-28T00:00:00.000Z,"['mineable', 'pow', 'sha-256', 'store-of-value...",21000000.00,19221256.00,...,38.27,360078487988.14,NaN,2022-12-01T05:17:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-01 05:18:39.846503
1,1,1027,Ethereum,ETH,ethereum,6238,2015-08-07T00:00:00.000Z,"['pos', 'smart-contracts', 'ethereum-ecosystem...",NaN,122373866.22,...,18.28,157424462374.31,NaN,2022-12-01T05:17:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-01 05:18:39.846503
2,2,825,Tether,USDT,tether,43020,2015-02-25T00:00:00.000Z,"['payments', 'stablecoin', 'asset-backed-stabl...",NaN,65362681003.31,...,7.59,73146090070.11,NaN,2022-12-01T05:17:00.000Z,1027.00,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7,2022-12-01 05:18:39.846503
3,3,1839,BNB,BNB,bnb,1147,2017-07-25T00:00:00.000Z,"['marketplace', 'centralized-exchange', 'payme...",200000000.00,159970653.62,...,5.51,59331030094.01,NaN,2022-12-01T05:17:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-01 05:18:39.846503
4,4,3408,USD Coin,USDC,usd-coin,7497,2018-10-08T00:00:00.000Z,"['medium-of-exchange', 'stablecoin', 'asset-ba...",NaN,43222909106.32,...,5.02,43230195922.56,NaN,2022-12-01T05:17:00.000Z,1027.00,Ethereum,ETH,ethereum,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,2022-12-01 05:18:39.846503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,10,6636,Polkadot,DOT,polkadot-new,435,2020-08-19T00:00:00.000Z,"['substrate', 'polkadot', 'binance-chain', 'po...",NaN,1141144111.48,...,0.75,7025345371.93,NaN,2022-12-03T12:58:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-03 13:01:17.461121
71,11,4943,Dai,DAI,multi-collateral-dai,1687,2019-11-22T00:00:00.000Z,"['defi', 'stablecoin', 'asset-backed-stablecoi...",NaN,5691184764.73,...,0.67,5691343373.81,NaN,2022-12-03T12:58:00.000Z,1027.00,Ethereum,ETH,ethereum,0x6b175474e89094c44da98b954eedeac495271d0f,2022-12-03 13:01:17.461121
72,12,2,Litecoin,LTC,litecoin,851,2013-04-28T00:00:00.000Z,"['mineable', 'pow', 'scrypt', 'medium-of-excha...",84000000.00,71747756.23,...,0.65,6458893257.25,NaN,2022-12-03T12:58:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-03 13:01:17.461121
73,13,5994,Shiba Inu,SHIB,shiba-inu,458,2020-08-01T00:00:00.000Z,"['memes', 'ethereum-ecosystem', 'doggone-dogge...",NaN,549063278876301.94,...,0.60,5481779237.84,NaN,2022-12-03T12:58:00.000Z,1027.00,Ethereum,ETH,ethereum,0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce,2022-12-03 13:01:17.461121
74,14,1958,TRON,TRX,tron,707,2017-09-13T00:00:00.000Z,"['media', 'payments', 'tron-ecosystem']",NaN,92127727952.95,...,0.58,4974678890.80,NaN,2022-12-03T12:58:00.000Z,NaN,NaN,NaN,NaN,NaN,2022-12-03 13:01:17.461121

In [82]:
df2 = df.groupby('name', sort =False)[['circulating_supply','quote.USD.market_cap_dominance']].mean()

In [83]:
df3 = df2.stack()
df3 # its series not dataframe
df4=df3.to_frame(name ='values')

In [59]:
index = pd.Index(range(int(df4.count())))
index

RangeIndex(start=0, stop=30, step=1)

In [84]:
df5 = df4.set_index(index)
df5

               values
0         19223225.00
1               38.18
2        122373866.22
3               18.22
4      65444431361.20
5                7.66
6        159970039.82
7                5.46
8      43237665494.80
9                5.06
10     22152178551.01
11               2.59
12     50260446248.00
13               2.32
14    132670764299.89
15               1.54
16     34446614164.26
17               1.30
18      8734317475.28
19               0.95
20      1141144111.48
21               0.75
22      5691184764.73
23               0.67
24        71747756.23
25               0.65
26 549063278876301.94
27               0.60
28     92127727952.95
29               0.58

In [85]:
df5 = df4.reset_index()
df6 = df5.rename(columns = {'level_1' : 'Supply_Cap_Dominance'})
df6

           name            Supply_Cap_Dominance             values
0       Bitcoin              circulating_supply        19223225.00
1       Bitcoin  quote.USD.market_cap_dominance              38.18
2      Ethereum              circulating_supply       122373866.22
3      Ethereum  quote.USD.market_cap_dominance              18.22
4        Tether              circulating_supply     65444431361.20
5        Tether  quote.USD.market_cap_dominance               7.66
6           BNB              circulating_supply       159970039.82
7           BNB  quote.USD.market_cap_dominance               5.46
8      USD Coin              circulating_supply     43237665494.80
9      USD Coin  quote.USD.market_cap_dominance               5.06
10  Binance USD              circulating_supply     22152178551.01
11  Binance USD  quote.USD.market_cap_dominance               2.59
12          XRP              circulating_supply     50260446248.00
13          XRP  quote.USD.market_cap_dominance               2.32
14     Dogecoin              circulating_supply    132670764299.89
15     Dogecoin  quote.USD.market_cap_dominance               1.54
16      Cardano              circulating_supply     34446614164.26
17      Cardano  quote.USD.market_cap_dominance               1.30
18      Polygon              circulating_supply      8734317475.28
19      Polygon  quote.USD.market_cap_dominance               0.95
20     Polkadot              circulating_supply      1141144111.48
21     Polkadot  quote.USD.market_cap_dominance               0.75
22          Dai              circulating_supply      5691184764.73
23          Dai  quote.USD.market_cap_dominance               0.67
24     Litecoin              circulating_supply        71747756.23
25     Litecoin  quote.USD.market_cap_dominance               0.65
26    Shiba Inu              circulating_supply 549063278876301.94
27    Shiba Inu  quote.USD.market_cap_dominance               0.60
28         TRON              circulating_supply     92127727952.95
29         TRON  quote.USD.market_cap_dominance               0.58